import type { Metadata } from "next";
import "./globals.css";
import ModalAddTodo from "@/components/ModalAddTodo";

export const metadata: Metadata = {
  title: "Trello Appwrite",
  description: "Generated by mksamuel",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={"bg-[#F5F6F8]"}>
        {children}
        <ModalAddTodo />
      </body>
    </html>
  );
}
